### ISSUE TITLE
Using com.google.android.gms:play-services-analytics:8.1.0 causes issues with proguard and other things

### ISSUE THREAD

**Issue by DazzyG** [qwasi/android-sdk#2]
Version 8.1 causes a compile time warning

```Warning: com.google.android.gms.internal.zzhu: can't find referenced class android.security.NetworkSecurityPolicy```

as well as a crash on start

```java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity```

It also significantly increases method count as referenced here: https://plus.google.com/+GoogleDevelopers/posts/HsSNWEQ6H4e

This issue is fixed in version 8.3+ but it's advisable to use the latest version (8.4 at time of writing) As all com.google.android.gms libraries need to use the same version any dependencies within qwasi apply to the client app

**Comment by ccoulton** [comment]
Good catch that was a special case for a customer wanting it at 8.1 sorry for inconvienance.  2.1.18 uses 8.4.  Currently working on a 8.3 version to try and mitagate the issue.

**Comment by ccoulton** [comment]
Closed latest version uses 8.4.0
