### ISSUE TITLE
Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by DazzyG** [qwasi/android-sdk#3]
QwasiSDK:2.1.19-4
QwasiGCMListener lines 59-60

```
mBaseContext = Qwasi.getContext();
mPM = mBaseContext.getPackageManager();
```

Qwasi.getContext() returns null so getPackageManager fails with a NullPointer.

As you are already in a service you don't need to do Qwasi.getContext because a service is a context.

**Comment by ccoulton** [comment]
I'll investigate this, but Reasoning is that even though it's in a service, the context of the service might not get back to the base context of the application. When is this crash happening with the GCMListener?

**Comment by ccoulton** [comment]
i made it a much safer reference in the newest build, but am worried about consistanicy issues and not getting the application context

**Comment by DazzyG** [comment]
It's happening in production so I've no control over the pushes that are being sent out. It would make sense that these are people that haven't opened the application, so Qwasi isn't being initialised.

The service will be fine for all of the places where you're trying to use the application context currently.

**Comment by ccoulton** [comment]
Ok

**Comment by ccoulton** [comment]
That is very serious, i'll build a hotfix making that a strong null check there make sure we get a context then?

**Comment by DazzyG** [comment]
Yes please @ccoulton It will be fine to replace all the instances of ```mBaseContext``` with ```this```

**Comment by ccoulton** [comment]
2.1.19-5 on OSSR fixes this issue tentivly closing this.

**Comment by DazzyG** [comment]
This unfortunately did not fix the problem. I think its because this work is being carried out in the constructor and not in onCreate, so any context related calls are returning null.

**Comment by ccoulton** [comment]
Life cycle issue moved inialization to Oncreate and had constructor call onCreate should be fixed.
